black main.py
black src/crypto/*.py
black src/DFixer/*.py
black src/domaingenerator/*.py
black src/grokreader/*.py
black src/utils/*.py
black src/ZReplicator/*.py
black src/config.py
black backend/*.py
black app.py
black worker.py
black worker_tasks.py